In [6]:
import numpy as np

In [11]:
marks=np.array([49,48,33,44,46,45])


In [12]:
marks

array([49, 48, 33, 44, 46, 45])

In [13]:
marks.max()


np.int64(49)

In [14]:
marks.mean()

np.float64(44.166666666666664)

In [15]:
marks.min()

np.int64(33)

In [16]:
marks*2

array([98, 96, 66, 88, 92, 90])

In [17]:
marks

array([49, 48, 33, 44, 46, 45])

In [18]:
marks>40

array([ True,  True, False,  True,  True,  True])

In [19]:
marks[marks>40]

array([49, 48, 44, 46, 45])

In [20]:
import pandas as pd

In [21]:
import pandas as pd

data = {
    "name": ["A", "B", "C", "D", "E"],
    "marks": [65, 78, 90, 82, 74]
}



In [22]:
df = pd.DataFrame(data)

In [23]:
df

name  marks
0    A     65
1    B     78
2    C     90
3    D     82
4    E     74

In [24]:
df.head()

name  marks
0    A     65
1    B     78
2    C     90
3    D     82
4    E     74

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    5 non-null      object
 1   marks   5 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes


In [26]:
df.describe

<bound method NDFrame.describe of   name  marks
0    A     65
1    B     78
2    C     90
3    D     82
4    E     74>

In [34]:
df["marks"].mean()

np.float64(77.8)

In [29]:
df["marks"].max()

90

In [30]:
df[df["marks"]>75]

name  marks
1    B     78
2    C     90
3    D     82

PANDAS MINI INSIGHT
Avg Marks
Number of students above 80
One Decision Sentence

In [35]:
import pandas as pd

In [46]:
import os
os.getcwd()



'C:\\Users\\harss\\45DAY ROADMAP'

In [47]:
os.listdir()

['.ipynb_checkpoints',
 'BASICSDAY_1.ipynb',
 'day2_numpy_pandas.ipynb',
 'Maths.csv',
 'Portuguese.csv',
 'student_scores.csv.txt']

In [48]:
import pandas as pd

In [49]:
df = pd.read_csv("student_scores.csv")

In [50]:
df.head()

student_id     name  maths  science  english
0           1    Alice     78       85       74
1           2      Bob     65       70       68
2           3  Charlie     90       92       88
3           4    David     55       60       58
4           5      Eva     82       88       80

In [52]:
df.shape

(10, 5)

In [53]:
df.columns

Index(['student_id', 'name', 'maths', 'science', 'english'], dtype='object')